export const wagmiAbi = [
  {
    inputs: [
      { internalType: "address", name: "aavePool", type: "address" },
      { internalType: "address", name: "gho", type: "address" },
      { internalType: "address[]", name: "tokenAddresses", type: "address[]" },
      {
        internalType: "address[]",
        name: "priceFeedAddresses",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "OnlySimulatedBackend", type: "error" },
  { inputs: [], name: "StreamLine__InsufficientCollateral", type: "error" },
  {
    inputs: [],
    name: "StreamLine__InsufficientDepositYieldForLoanInterest",
    type: "error",
  },
  {
    inputs: [],
    name: "StreamLine__InsufficientTokenDepositForStream",
    type: "error",
  },
  { inputs: [], name: "StreamLine__InvalidReceiverAddress", type: "error" },
  { inputs: [], name: "StreamLine__MustBeGreaterThanZero", type: "error" },
  { inputs: [], name: "StreamLine__NeedsMoreThanZero", type: "error" },
  {
    inputs: [],
    name: "StreamLine__TokenAddressesAndPriceFeedAddressesAmountsDontMatch",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "StreamLine__TokenNotAllowed",
    type: "error",
  },
  { inputs: [], name: "StreamLine__TransferFailed", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "Borrowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "interval",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "duaration",
        type: "uint256",
      },
    ],
    name: "NewStream",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "Repaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "Supplied",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "id", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "period",
        type: "uint256",
      },
    ],
    name: "TokenDeposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdraToken",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "collateralTokenAddress",
        type: "address",
      },
      { internalType: "uint256", name: "borrowAmount", type: "uint256" },
    ],
    name: "borrowToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum StreamLine.DepositTokenType",
        name: "depositTokenType",
        type: "uint8",
      },
      { internalType: "address", name: "depositTokenAddress", type: "address" },
      { internalType: "uint256", name: "depositAmountWei", type: "uint256" },
      { internalType: "uint256", name: "depositPeriodDays", type: "uint256" },
      {
        internalType: "enum StreamLine.BorrowTokenType",
        name: "borrowTokentype",
        type: "uint8",
      },
      { internalType: "address", name: "borrowTokenAddress", type: "address" },
      { internalType: "uint256", name: "borrowedAmountWei", type: "uint256" },
      { internalType: "uint256", name: "borrowPeriodDays", type: "uint256" },
    ],
    name: "calculateCollateralForDebtCoverage",
    outputs: [
      { internalType: "uint256", name: "debtInterestInEther", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum StreamLine.DepositTokenType",
        name: "tokenType",
        type: "uint8",
      },
      { internalType: "uint256", name: "depositAmountWei", type: "uint256" },
      { internalType: "uint256", name: "depositPeriodDays", type: "uint256" },
    ],
    name: "calculateDepositInterest",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum StreamLine.DepositTokenType",
        name: "tokenType",
        type: "uint8",
      },
      { internalType: "uint256", name: "depositAmountWei", type: "uint256" },
      { internalType: "uint256", name: "depositPeriodDays", type: "uint256" },
    ],
    name: "calculateFinalAsset",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum StreamLine.BorrowTokenType",
        name: "tokenType",
        type: "uint8",
      },
      { internalType: "uint256", name: "borrowedAmountWei", type: "uint256" },
      { internalType: "uint256", name: "borrowPeriodDays", type: "uint256" },
    ],
    name: "calculateFinalDebt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum StreamLine.BorrowTokenType",
        name: "tokenType",
        type: "uint8",
      },
      { internalType: "uint256", name: "borrowedAmountWei", type: "uint256" },
      { internalType: "uint256", name: "borrowPeriodDays", type: "uint256" },
    ],
    name: "calculateLoanRepaymentInterest",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
      { internalType: "uint256", name: "amountCollateral", type: "uint256" },
    ],
    name: "calculateMaxTokenToBorrow",
    outputs: [
      { internalType: "uint256", name: "maxGhoToBorrow", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    name: "checkUpkeep",
    outputs: [
      { internalType: "bool", name: "upkeepNeeded", type: "bool" },
      { internalType: "bytes", name: "performData", type: "bytes" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "depositId", type: "uint256" },
      {
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
      { internalType: "uint256", name: "amountCollateral", type: "uint256" },
      { internalType: "uint256", name: "depositPeriodDays", type: "uint256" },
    ],
    name: "depositCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getAccountInformation",
    outputs: [
      { internalType: "uint256", name: "totalCollateralBase", type: "uint256" },
      { internalType: "uint256", name: "totalDebtBase", type: "uint256" },
      {
        internalType: "uint256",
        name: "availableBorrowsBase",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentLiquidationThreshold",
        type: "uint256",
      },
      { internalType: "uint256", name: "ltv", type: "uint256" },
      { internalType: "uint256", name: "healthFactor", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAdditionalFeedPrecision",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "getCollateralTokenPriceFeed",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCollateralTokens",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDAITokenCurrentAPR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "depositId", type: "uint256" },
    ],
    name: "getDepositPeriodForUser",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGhoAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLINKTokenCurrentAPR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolAddress",
    outputs: [{ internalType: "contract IPool", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrecision",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "tokenCollateral", type: "address" },
    ],
    name: "getUserBorrowedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "depositToken", type: "address" },
    ],
    name: "getUserDepositAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "depositId", type: "uint256" },
    ],
    name: "getUserDepositInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "depositId", type: "uint256" },
          {
            internalType: "address",
            name: "tokenCollateralAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountCollateral",
            type: "uint256",
          },
          { internalType: "uint256", name: "depositPeriod", type: "uint256" },
        ],
        internalType: "struct StreamLine.UserDeposit",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "streamId", type: "uint256" },
    ],
    name: "getUserStreamInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "orderId", type: "uint256" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "uint256", name: "streamAmount", type: "uint256" },
          { internalType: "uint256", name: "interval", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "uint256", name: "lastTimeStamp", type: "uint256" },
        ],
        internalType: "struct StreamLine.Stream",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "tokenCollateral", type: "address" },
    ],
    name: "getUserSuppliedCollateralAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "orderId", type: "uint256" },
      {
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "totalStreamAmount", type: "uint256" },
      { internalType: "address", name: "receiverAddress", type: "address" },
      { internalType: "uint256", name: "interval", type: "uint256" },
      { internalType: "uint256", name: "duration", type: "uint256" },
    ],
    name: "openStream",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "performData", type: "bytes" }],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "collateralTokenAddress",
        type: "address",
      },
      { internalType: "uint256", name: "repayAmount", type: "uint256" },
    ],
    name: "repayToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
      { internalType: "uint256", name: "collateralAmount", type: "uint256" },
    ],
    name: "supplyCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
      { internalType: "uint256", name: "amountCollateral", type: "uint256" },
    ],
    name: "withdrawToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
]  as const;
